// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Auftraege(arg1) {
  return window['go']['main']['App']['Auftraege'](arg1);
}

export function Auftrag(arg1) {
  return window['go']['main']['App']['Auftrag'](arg1);
}

export function AuftragAbbrechen(arg1) {
  return window['go']['main']['App']['AuftragAbbrechen'](arg1);
}

export function AuftragStarten(arg1, arg2, arg3) {
  return window['go']['main']['App']['AuftragStarten'](arg1, arg2, arg3);
}

export function AuftragVeroeffentlichen(arg1, arg2, arg3) {
  return window['go']['main']['App']['AuftragVeroeffentlichen'](arg1, arg2, arg3);
}

export function Binden(arg1, arg2) {
  return window['go']['main']['App']['Binden'](arg1, arg2);
}

export function BytesDrucken(arg1, arg2) {
  return window['go']['main']['App']['BytesDrucken'](arg1, arg2);
}

export function DateienWaehlen() {
  return window['go']['main']['App']['DateienWaehlen']();
}

export function Drucken(arg1) {
  return window['go']['main']['App']['Drucken'](arg1);
}

export function Druckfassung(arg1, arg2) {
  return window['go']['main']['App']['Druckfassung'](arg1, arg2);
}

export function Exportieren(arg1, arg2, arg3) {
  return window['go']['main']['App']['Exportieren'](arg1, arg2, arg3);
}

export function Extrahieren(arg1, arg2, arg3) {
  return window['go']['main']['App']['Extrahieren'](arg1, arg2, arg3);
}

export function Info(arg1) {
  return window['go']['main']['App']['Info'](arg1);
}

export function KopieSichern(arg1) {
  return window['go']['main']['App']['KopieSichern'](arg1);
}

export function Lizenzen() {
  return window['go']['main']['App']['Lizenzen']();
}

export function MenueSprache(arg1) {
  return window['go']['main']['App']['MenueSprache'](arg1);
}

export function Modell(arg1) {
  return window['go']['main']['App']['Modell'](arg1);
}

export function OeffnenDialog() {
  return window['go']['main']['App']['OeffnenDialog']();
}

export function QuelleInfo(arg1) {
  return window['go']['main']['App']['QuelleInfo'](arg1);
}

export function RechteKennwortPruefen(arg1, arg2) {
  return window['go']['main']['App']['RechteKennwortPruefen'](arg1, arg2);
}

export function Schliessen(arg1) {
  return window['go']['main']['App']['Schliessen'](arg1);
}

export function Schnelldruck(arg1) {
  return window['go']['main']['App']['Schnelldruck'](arg1);
}

export function SeiteLiefern(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SeiteLiefern'](arg1, arg2, arg3, arg4);
}

export function Seitenarten(arg1) {
  return window['go']['main']['App']['Seitenarten'](arg1);
}

export function Speichern(arg1, arg2, arg3) {
  return window['go']['main']['App']['Speichern'](arg1, arg2, arg3);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function ZielWaehlen(arg1) {
  return window['go']['main']['App']['ZielWaehlen'](arg1);
}

export function Zuletzt() {
  return window['go']['main']['App']['Zuletzt']();
}

export function ZuletztOeffnen(arg1) {
  return window['go']['main']['App']['ZuletztOeffnen'](arg1);
}
