// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {export} from '../models';

export function Auftraege(arg1:string):Promise<Array<main.Auftrag>>;

export function Auftrag(arg1:string):Promise<main.Auftrag>;

export function AuftragAbbrechen(arg1:string):Promise<main.Auftrag>;

export function AuftragStarten(arg1:string,arg2:main.AuftragBefehl,arg3:string):Promise<main.Auftrag>;

export function AuftragVeroeffentlichen(arg1:string,arg2:main.AuftragCommit,arg3:string):Promise<main.Ergebnis>;

export function Binden(arg1:main.BindeBefehl,arg2:string):Promise<main.Ergebnis>;

export function BytesDrucken(arg1:string,arg2:string):Promise<void>;

export function DateienWaehlen():Promise<Array<main.DateiWahl>>;

export function Drucken(arg1:string):Promise<void>;

export function Druckfassung(arg1:string,arg2:main.DruckBefehl):Promise<string>;

export function Exportieren(arg1:string,arg2:main.ExportBefehl,arg3:string):Promise<main.ExportErgebnis>;

export function Extrahieren(arg1:string,arg2:main.ExtraktBefehl,arg3:string):Promise<main.ExtraktErgebnis>;

export function Info(arg1:string):Promise<main.Info>;

export function KopieSichern(arg1:string):Promise<void>;

export function Lizenzen():Promise<main.Lizenzauskunft>;

export function MenueSprache(arg1:Record<string, string>):Promise<void>;

export function Modell(arg1:string):Promise<export.Dokument>;

export function OeffnenDialog():Promise<main.Geoeffnet>;

export function QuelleInfo(arg1:string):Promise<main.Info>;

export function RechteKennwortPruefen(arg1:string,arg2:string):Promise<void>;

export function Schliessen(arg1:string):Promise<void>;

export function Schnelldruck(arg1:string):Promise<void>;

export function SeiteLiefern(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function Seitenarten(arg1:string):Promise<main.Seitenarten>;

export function Speichern(arg1:string,arg2:main.CommitBefehl,arg3:string):Promise<main.Ergebnis>;

export function Start():Promise<main.StartInfo>;

export function ZielWaehlen(arg1:main.ZielAnfrage):Promise<main.Ziel>;

export function Zuletzt():Promise<Array<main.ZuletztEintrag>>;

export function ZuletztOeffnen(arg1:string):Promise<main.Geoeffnet>;
